### ISSUE TITLE
Tests don't support Python 3

### ISSUE THREAD

**Issue by coreycb** [dvarrazzo/py-setproctitle#50]
I'm trying to get tests running for the Ubuntu package and while py2 is ok, the code currently won't run for py3.  I'm not sure if this is the only py3 failure or of it's just the start.

======================================================================
ERROR: Failure: SyntaxError (Missing parentheses in call to 'print' (setproctitle_test.py, line 413))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/tests/setproctitle_test.py", line 413
    print out
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by scopatz** [comment]
Don't know anything about the tests, but setproctitle does seem to run on py3k.

**Comment by dvarrazzo** [comment]
Yes they do:

    make PYTHON=python3 check

**Comment by turicas** [comment]
@dvarrazzo, I think the error will happen only if some test fail, look into [tests/setproctitle_test.py#L413](https://github.com/dvarrazzo/py-setproctitle/blob/master/tests/setproctitle_test.py#L413) -- the `print` as a statement is not supported by Python3. The problem is inside `run_script` function and this code is not converted to Python3.

**Comment by dvarrazzo** [comment]
Yes it is: check the makefile. The code is converted by `2to3` (as it was customary when `setproctitle` was developed). Hint: look into the `py3` directory.

**Comment by dvarrazzo** [comment]
```
piro@risotto:~/src/setproctitle$ egrep 'print.*out' py3/tests/setproctitle_test.py
            print(out)
```

**Comment by turicas** [comment]
Ah, ok, I was not looking into `Makefile`.  Probable @coreycb's problem was trying to run `nosetests` with Python3 without converting the tests to Python3 with the `Makefile`.

**Comment by coreycb** [comment]
Converting the test file with 2to3 worked. Thanks.
