### ISSUE TITLE
py-setproctitle install fails on windows 10 Python 3.7.0

### ISSUE THREAD

**Issue by laksh225** [dvarrazzo/py-setproctitle#79]
I tried to install py-setproctitle for Windows 10. But got this error.
I have tried building from source here after pip gave the same error.
I have already install Microsoft Visual Studio 2019 C++ build tools.

Here is the log:
PS C:\WINDOWS\system32> cd F:\Github\py-setproctitle\
PS F:\Github\py-setproctitle> python .\setup.py install
running install
running bdist_egg
running egg_info
creating setproctitle.egg-info
writing setproctitle.egg-info\PKG-INFO
writing dependency_links to setproctitle.egg-info\dependency_links.txt
writing top-level names to setproctitle.egg-info\top_level.txt
writing manifest file 'setproctitle.egg-info\SOURCES.txt'
reading manifest file 'setproctitle.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
writing manifest file 'setproctitle.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'setproctitle' extension
b'\\\x00W\x00i\x00n\x00S\x00C\x00P\x00\\\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'
Traceback (most recent call last):
  File ".\setup.py", line 99, in <module>
    **kwargs
  File "C:\Program Files\Python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Program Files\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Program Files\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Program Files\Python37\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Program Files\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Program Files\Python37\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Program Files\Python37\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Program Files\Python37\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Program Files\Python37\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Program Files\Python37\lib\distutils\_msvccompiler.py", line 345, in compile
    self.initialize()
  File "C:\Program Files\Python37\lib\distutils\_msvccompiler.py", line 238, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
    return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
  File "C:\Program Files\Python37\lib\site-packages\setuptools\msvc.py", line 1620, in return_env
    if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
  File "C:\Program Files\Python37\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by dvarrazzo** [comment]
Building for windows maybe is possible but currently is not supported. I am available to work on it but not for free. See #47
